# Generated by Django 5.0.7 on 2024-08-05 11:16

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='email',
            field=models.EmailField(default='default@noreply.com', max_length=254),
        ),
        migrations.AddField(
            model_name='task',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='task',
            name='gff_label',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='lineage',
            field=models.CharField(choices=[('land_plants', 'Land plant'), ('vertebrates', 'Vertebrates'), ('invertebrates', 'Invertebrates'), ('fungi', 'Fungi')], default=datetime.datetime(2024, 8, 5, 11, 16, 2, 665048, tzinfo=datetime.timezone.utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='use_demo_file',
            field=models.BooleanField(default=False),
        ),
    ]
