# Generated by Django 5.0.7 on 2024-08-05 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_email_task_file_task_gff_label_task_lineage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='gff_file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='task',
            name='gff_label',
            field=models.CharField(default='default_label', max_length=255),
        ),
    ]
